/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package danaral;

import java.awt.Color;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Manel
 */
public class CerereRaportLunar extends javax.swing.JFrame {

    /**
     * Creates new form CerereRaportLunar
     * @param raportSelectat
     */
    JCheckBox checkBoxes[]=new JCheckBox[31];
    int CHECKBOX_HEIGHT=30;
    public CerereRaportLunar() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        ani=Danaral.getDanaral().cititor.getAni();
        DefaultComboBoxModel model=(DefaultComboBoxModel)jComboBox2.getModel();
        for (Integer an:ani){
            model.addElement(an);
        }
        jComboBox2.setModel(model);

        for (int i = 0; i < checkBoxes.length; i++) {
            checkBoxes[i] = new JCheckBox((i + 1) < 10 ? "0" + (i+1) : (i+1) + "");
            checkBoxes[i].setSelected(true);
            checkBoxes[i].setFocusable(false);
            checkBoxes[i].addChangeListener(new ChangeListener() {
                @Override
                public void stateChanged(ChangeEvent ce) {
                    JCheckBox source=(JCheckBox)ce.getSource();
                    if (source.isSelected()){
                        source.setBackground(new Color(240,240,240));
                    }else{
                        source.setBackground(new Color(128,0,32));
                    }
                }
            });
            jPanel1.add(checkBoxes[i]);
        }

        setLocationRelativeTo(null);
    }
    int []ani;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Interogare lună");
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Luna :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ianuarie", "Februarie", "Martie", "Aprilie", "Mai", "Iunie", "Iulie", "August", "Septembrie", "Octombrie", "Noiembrie", "Decembrie" }));
        jComboBox1.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("An :");

        jComboBox2.setFocusable(false);

        jButton1.setText("Generează");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane2.getVerticalScrollBar().setUnitIncrement(51);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(jPanel1);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Zile :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static String RAPORT_SELECTAT=Danaral.RAPORT_TIP_1;
    
    
    boolean sameDay(RaportZi raport,int zi){
        int ziRaport=Integer.valueOf(raport.data.split(":")[1]);
        return zi==ziRaport;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (RAPORT_SELECTAT.equals(Danaral.RAPORT_TIP_1)) {
            ActivitatiDetaliate act = new ActivitatiDetaliate();
            String data = "01:01:2020";
            int luna = jComboBox1.getSelectedIndex() + 1;
            String an = "2020";
            System.out.println(jComboBox2.getSelectedItem());
            an = Integer.toString((Integer) jComboBox2.getSelectedItem());
            String lunaString = (luna < 10 ? "0" : "") + luna;
            data = lunaString + ":01:" + an;
            System.out.println("Vrea data" + data);
            List<RaportZi> raport = Danaral.getDanaral().cititor.getRaportPeLuna(data);
            System.out.println("dimensiune raport " + raport.size());
            
            int zileAlese=0;
            String zileAleseString="\n";
            for (int i=0;i<checkBoxes.length;i++){
                if (checkBoxes[i].isSelected()){
                    zileAlese++;
                    zileAleseString+=checkBoxes[i].getText()+"\n";
                }else{
                    int ziCheckBox=Integer.valueOf(checkBoxes[i].getText());
                    raport.removeIf(_raport_->(sameDay(_raport_,ziCheckBox)));
                }
            }
            System.out.println("Zile alese: "+zileAlese+" continut:"+zileAleseString);
            
            try {
                act.set(raport);
            } catch (java.lang.IndexOutOfBoundsException ex) {
                JOptionPane.showMessageDialog(this, "Nu am gasit date in " + data);
            }
        } else if (RAPORT_SELECTAT.equals(Danaral.RAPORT_NOAPTE)) {
            RaportTuraNoapte act = new RaportTuraNoapte();
            String data = "01:01:2020";
            int luna = jComboBox1.getSelectedIndex() + 1;
            String an = "2020";
            System.out.println(jComboBox2.getSelectedItem());
            an = Integer.toString((Integer) jComboBox2.getSelectedItem());
            String lunaString = (luna < 10 ? "0" : "") + luna;
            data = lunaString + ":01:" + an;
            System.out.println("Vrea data" + data);
            List<RaportZi> raport = Danaral.getDanaral().cititor.getRaportPeLuna(data);
            System.out.println("dimensiune raport " + raport.size());

            int zileAlese = 0;
            String zileAleseString = "\n";
            for (int i = 0; i < checkBoxes.length; i++) {
                if (checkBoxes[i].isSelected()) {
                    zileAlese++;
                    zileAleseString += checkBoxes[i].getText() + "\n";
                } else {
                    int ziCheckBox = Integer.valueOf(checkBoxes[i].getText());
                    raport.removeIf(_raport_ -> (sameDay(_raport_, ziCheckBox)));
                }
            }
            System.out.println("Zile alese: " + zileAlese + " continut:" + zileAleseString);

            try {
                act.set(raport);
            } catch (java.lang.IndexOutOfBoundsException ex) {
                JOptionPane.showMessageDialog(this, "Nu am gasit date in " + data);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    @Deprecated
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CerereRaportLunar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CerereRaportLunar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CerereRaportLunar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CerereRaportLunar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CerereRaportLunar().setVisible(true);
            }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CerereRaportLunar().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
